---
:environment: production
:daemon: true
:concurrency: 1
:pidfile: tmp/pids/worker_openproject_git_hosting.pid
:logfile: log/worker_openproject_git_hosting.log
:require: ./
:verbose: true
:queues:
  - [git_hosting, 1]
